app = "terminator"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  BOT_URL = "https://terminator.fly.dev/"
  BOT_PORT = "8443"
  ENV = "production"

[[services]]
  internal_port = 8443
  protocol = "tcp"
  force_https = true
  [[services.ports]]
    handlers = ["tls", "http"]
    port = 8443